#cloud-config
package_update: true
package_upgrade: true
runcmd:
  - [ curl, -fsSL, https://get.docker.com, -o, install-docker.sh ]
  - [ sudo, sh, install-docker.sh ]
  - [ sh, -c, 'sudo usermod -aG docker $USER' ]
  - [ sudo, systemctl, enable, docker ]
  - [ sudo, systemctl, start, docker ]

write_files:
  - path: ~/run-jenkins.sh
    permissions: '0777'
    content: |
      # Build and run Jenkins Docker container
      docker build -t jenkins .
      docker run -d -p 8080:8080 -p 50000:50000 jenkins

runcmd:
  - [ sh, ~/run-jenkins.sh ]
